language: go
go:
    - "1.5.1"
addons:
  apt:
    packages:
      - libflac-dev
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - pip install --user codecov
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
after_success:
  - codecov
